baseURL = "https://lucasmoura.github.io/"
languageCode = "en-us"
title = "lucasmoura's blog"
theme = "kiera"

pygmentsCodeFences = true

disqusShortname = "https-lucasmoura-github-io"
googleAnalytics = "" #Google Analytics ID

[author]
    name = "Lucas Moura"       #Author name
    github = "lucasmoura"     #Github username
    linkedin = "lucas-albuquerque-medeiros-de-moura-941644152"   #LinkedIn username

[params]
    tagline = "Another variable in the Deep Learning hyperspace"

[permalinks]
  posts = "blog/:year/:month/:day/:title/"
